In [1]:
import pandas as pd
import random
import requests
import json

import time

In [2]:
url = 'http://127.0.0.1:5000'

In [3]:
# data = pd.read_csv('../data/dataset_edit.csv', index_col=None)
data = pd.read_csv('../../ml_datasets/dataset_edit.csv', index_col=None)
# data = pd.read_csv('../../ml_datasets/izaque/dataset_edit.csv', index_col=None)
data2 = data
data

      type_of_failure  time_repair   cost  criticality  humid  temp  label
0                   7     0.363742  0.522        0.499     61    97      0
1                   5     0.297000  0.485        0.307     63   112      0
2                   9     0.383106 -0.075        0.798      6    40      1
3                   4     0.300732  0.553        0.531     48   141      0
4                   2     0.127000  0.335        0.367     74   148      0
...               ...          ...    ...          ...    ...   ...    ...
9994                3     0.391921  0.518        0.508      6    56      0
9995                3     0.102000  0.494        0.272     56    88      0
9996                9     0.339469  0.277        0.456     80   142      0
9997                7     0.277222  0.457        0.424     61    99      0
9998                9     0.250000  0.309        0.282     42    92      0

[9999 rows x 7 columns]

In [4]:
data.sample(5)

      type_of_failure  time_repair   cost  criticality  humid  temp  label
8496                8     0.323000  0.345        0.243     44    35      0
7398                7     0.240000  0.365        0.283     78   137      0
336                 2     0.221469  0.577        0.418     61   130      0
2676                4     0.301652  0.718        0.720     85    24      1
9286               10     0.248149  0.517        0.499     24    59      0

In [5]:
data.describe()

,type_of_failure,time_repair,cost,criticality,humid,temp,label
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000
mean,5.471947,0.325987,0.427160,0.474373,45.022102,86.671067,0.170317
std,2.857660,0.235613,0.224073,0.176080,23.357811,36.813081,0.375930
min,1.000000,-0.630466,-0.843000,0.000000,5.000000,24.000000,0.000000
25%,3.000000,0.212446,0.295000,0.325000,25.000000,54.000000,0.000000
50%,5.000000,0.282000,0.422000,0.476000,45.000000,86.000000,0.000000
75%,8.000000,0.343999,0.539000,0.559000,65.000000,119.000000,0.000000
max,10.000000,1.977825,1.712000,0.912000,85.000000,150.000000,1.000000

In [6]:
class bold_color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

In [7]:
type_failure = (1,10)
time_repair = (0.1,2)
cost = (0,2)
criticality = (0,0.9999)
humid = (0,100)
temp = (0,500)

In [8]:
def generate_new_param():
  params = {
    "type_of_failure": random.uniform(type_failure[0], type_failure[1]),
    "time_repair": random.uniform(time_repair[0], time_repair[1]),
    "cost": random.uniform(cost[0], cost[1]),
    "criticality": random.uniform(criticality[0], criticality[1]),
    "humid": random.uniform(humid[0], humid[1]),
    "temp": random.uniform(temp[0], temp[1])
  }
  return params, random.randint(1, 10)

In [15]:
# print(f'Status \t Result')
new_results = []
for i in range(0,10000):
    new_data, machine = generate_new_param()
    response = requests.post(url+'/predict',data=json.dumps(new_data))
    result = response.json()
    predict = 'OK' if result['prediction'] == 0 else 'FAIL'
    # print(f'{predict}')
    if result["prediction"] and (result["score"] > 0.8):
        print(f'{bold_color.RED}ERROR:{bold_color.END} Machine {machine} stops running, possible failure.')
    elif result["prediction"] and (result["score"] > 0.7 and result["score"] < 0.8):
        print(f'{bold_color.YELLOW}WARNING:{bold_color.END} Machine {machine} may fail, perform maintenance.')
    print(f'**{predict} - {(result["score"]*100):.2f}%**')
    new_data['label'] = (result['prediction'])
    # print(new_data)
    new_results.append(new_data)
    # data2.append(new_data, ignore_index=True)
    # pd.concat(data2)

ERROR: Machine 2 stops running, possible failure.
ERROR: Machine 6 stops running, possible failure.
WARNING: Machine 10 may fail, perform maintenance.
WARNING: Machine 7 may fail, perform maintenance.
ERROR: Machine 8 stops running, possible failure.
ERROR: Machine 6 stops running, possible failure.
ERROR: Machine 3 stops running, possible failure.
WARNING: Machine 9 may fail, perform maintenance.
ERROR: Machine 4 stops running, possible failure.
ERROR: Machine 6 stops running, possible failure.
ERROR: Machine 3 stops running, possible failure.
ERROR: Machine 8 stops running, possible failure.
WARNING: Machine 9 may fail, perform maintenance.
ERROR: Machine 10 stops running, possible failure.
ERROR: Machine 3 stops running, possible failure.
ERROR: Machine 5 stops running, possible failure.
ERROR: Machine 4 stops running, possible failure.
ERROR: Machine 8 stops running, possible failure.
ERROR: Machine 3 stops running, possible failure.
WARNING: Machine 9 may fail, perform maintenance.
ERROR: Machine 9 stops running, possible failure.
ERROR: Machine 2 stops running, possible failure.
ERROR: Machine 9 stops running, possible failure.
WARNING: Machine 2 may fail, perform maintenance.
ERROR: Machine 6 stops running, possible failure.
ERROR: Machine 6 stops running, possible failure.
ERROR: Machine 4 stops running, possible failure.
WARNING: Machine 10 may fail, perform maintenance.
WARNING: Machine 2 may fail, perform maintenance.
ERROR: Machine 7 stops running, possible failure.
ERROR: Machine 6 stops running, possible failure.
ERROR: Machine 7 stops running, possible failure.
WARNING: Machine 4 may fail, perform maintenance.

In [10]:
# data3.to_csv('../../ml_datasets/dataset_testing.csv', index=False)

In [11]:
new_df = pd.DataFrame(data=new_results, columns=new_results[0].keys())

In [12]:
data3 = pd.concat([new_df, data2], ignore_index=True)
# data3

In [13]:
# data = pd.read_csv('../../ml_datasets/dataset_edit.csv', index_col=None)
# data3=data
data3.to_csv('../../ml_datasets/dataset_testing.csv', index=False)

In [14]:
# # print(f'Status \t Result')
# for j in range(0,3):
#     new_results = []
#     for i in range(0,500):
#         new_data = generate_new_param()
#         response = requests.post(url+'/predict',data=json.dumps(new_data))
#         result = response.json()
#         predict = 'OK' if result['prediction'] == 0 else 'FAIL'
#         # print(f'{predict}')
#         print(f'{predict} \t {(result["score"]*100):.2f}%')
#         new_data['label'] = (result['prediction'])
#         # print(new_data)
#         new_results.append(new_data)
#         # data2.append(new_data, ignore_index=True)
#         # pd.concat(data2)
        
#     new_df = pd.DataFrame(data=new_results, columns=new_results[0].keys())

#     data3 = pd.concat([new_df, data], ignore_index=True)

#     data3.to_csv('../../ml_datasets/dataset_testing.csv', index=False)

#     print(f"New data interation {j}")
#     print("Update api")
#     time.sleep(120)
#     data2 = data3.sample(9000)