In [59]:
import pandas as pd
import random
import requests
import json

import time

In [60]:
url = 'http://127.0.0.1:5000'

In [61]:
# data = pd.read_csv('../data/dataset_edit.csv', index_col=None)
data = pd.read_csv('../../ml_datasets/izaque/dataset_edit.csv', index_col=None)
data2 = data
data

      type_of_failure  time_repair   cost  criticality  humid  temp  label
0                   7     0.363742  0.522        0.499     61    97      0
1                   5     0.297000  0.485        0.307     63   112      0
2                   9     0.383106 -0.075        0.798      6    40      1
3                   4     0.300732  0.553        0.531     48   141      0
4                   2     0.127000  0.335        0.367     74   148      0
...               ...          ...    ...          ...    ...   ...    ...
9994                3     0.391921  0.518        0.508      6    56      0
9995                3     0.102000  0.494        0.272     56    88      0
9996                9     0.339469  0.277        0.456     80   142      0
9997                7     0.277222  0.457        0.424     61    99      0
9998                9     0.250000  0.309        0.282     42    92      0

[9999 rows x 7 columns]

In [62]:
data.sample(5)

      type_of_failure  time_repair   cost  criticality  humid  temp  label
3982                2     0.257968  0.587        0.559     50   103      0
885                 2     0.332661  0.299        0.811     10   118      1
2022               10     0.259198  0.623        0.470     35    86      0
2367                1     0.254000  0.398        0.299     40   102      0
667                10     0.337000  0.183        0.388     11    61      0

In [63]:
data.describe()

,type_of_failure,time_repair,cost,criticality,humid,temp,label
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000
mean,5.471947,0.325987,0.427160,0.474373,45.022102,86.671067,0.170317
std,2.857660,0.235613,0.224073,0.176080,23.357811,36.813081,0.375930
min,1.000000,-0.630466,-0.843000,0.000000,5.000000,24.000000,0.000000
25%,3.000000,0.212446,0.295000,0.325000,25.000000,54.000000,0.000000
50%,5.000000,0.282000,0.422000,0.476000,45.000000,86.000000,0.000000
75%,8.000000,0.343999,0.539000,0.559000,65.000000,119.000000,0.000000
max,10.000000,1.977825,1.712000,0.912000,85.000000,150.000000,1.000000

In [64]:
type_failure = (1,10)
time_repair = (0.1,2)
cost = (0,2)
criticality = (0,0.9999)
humid = (0,100)
temp = (0,500)

In [65]:
def generate_new_param():
  params = {
    "type_of_failure": random.uniform(type_failure[0], type_failure[1]),
    "time_repair": random.uniform(time_repair[0], time_repair[1]),
    "cost": random.uniform(cost[0], cost[1]),
    "criticality": random.uniform(criticality[0], criticality[1]),
    "humid": random.uniform(humid[0], humid[1]),
    "temp": random.uniform(temp[0], temp[1])
  }
  return params, random.randint(1, 10)

In [66]:
# print(f'Status \t Result')
new_results = []
for i in range(0,100):
    new_data, machine = generate_new_param()
    response = requests.post(url+'/predict',data=json.dumps(new_data))
    result = response.json()
    predict = 'OK' if result['prediction'] == 0 else 'FAIL'
    # print(f'{predict}')
    if result["prediction"] and (result["score"] > 0.8):
        print(f'ALERT: the machine {machine} stoped work - possible failure')
    elif result["prediction"] and (result["score"] > 0.7 and result["score"] < 0.8):
        print(f'WARNING: the machine {machine} may fail, take the necessary care')
    print(f'{predict} \t {(result["score"]*100):.2f}%')
    new_data['label'] = (result['prediction'])
    # print(new_data)
    new_results.append(new_data)
    # data2.append(new_data, ignore_index=True)
    # pd.concat(data2)

OK 	 59.87%
WARNING: the machine 3 may fail, take the necessary care
FAIL 	 77.07%
OK 	 75.82%
ALERT: the machine 10 stoped work - possible failure
FAIL 	 87.72%
ALERT: the machine 1 stoped work - possible failure
FAIL 	 87.42%
ALERT: the machine 4 stoped work - possible failure
FAIL 	 87.72%
OK 	 66.23%
OK 	 69.13%
OK 	 58.57%
OK 	 66.52%
WARNING: the machine 7 may fail, take the necessary care
FAIL 	 76.27%
OK 	 75.18%
ALERT: the machine 10 stoped work - possible failure
FAIL 	 87.72%
OK 	 74.87%
ALERT: the machine 10 stoped work - possible failure
FAIL 	 82.79%
OK 	 72.84%
OK 	 68.88%
OK 	 59.87%
OK 	 69.43%
FAIL 	 61.26%
OK 	 61.09%
OK 	 61.50%
WARNING: the machine 4 may fail, take the necessary care
FAIL 	 75.33%
FAIL 	 52.85%
OK 	 57.51%
OK 	 60.28%
WARNING: the machine 1 may fail, take the necessary care
FAIL 	 75.33%
OK 	 69.43%
ALERT: the machine 7 stoped work - possible failure
FAIL 	 80.67%
OK 	 69.43%
OK 	 72.75%
ALERT: the machine 2 stoped work - possible failure
FAIL 	 86.55%
OK 	 60.22%
OK 	 62.71%
OK 	 61.50%
ALERT: the machine 5 stoped work - possible failure
FAIL 	 80.86%
OK 	 74.12%
ALERT: the machine 5 stoped work - possible failure
FAIL 	 88.19%
OK 	 71.91%
ALERT: the machine 1 stoped work - possible failure
FAIL 	 83.80%
OK 	 69.43%
OK 	 68.56%
WARNING: the machine 9 may fail, take the necessary care
FAIL 	 78.43%
OK 	 58.99%
OK 	 58.98%
ALERT: the machine 9 stoped work - possible failure
FAIL 	 89.09%
OK 	 53.17%
OK 	 71.37%
WARNING: the machine 5 may fail, take the necessary care
FAIL 	 78.43%
OK 	 61.09%
ALERT: the machine 1 stoped work - possible failure
FAIL 	 87.72%
OK 	 66.07%
OK 	 68.29%
OK 	 67.74%
OK 	 74.88%
WARNING: the machine 6 may fail, take the necessary care
FAIL 	 79.82%
WARNING: the machine 5 may fail, take the necessary care
FAIL 	 74.04%
OK 	 69.79%
OK 	 59.87%
OK 	 60.48%
OK 	 69.43%
OK 	 71.67%
FAIL 	 55.76%
FAIL 	 55.19%
OK 	 59.87%
OK 	 77.10%
ALERT: the machine 3 stoped work - possible failure
FAIL 	 84.29%
OK 	 74.87%
OK 	 75.87%
OK 	 58.59%
OK 	 61.50%
OK 	 68.28%
OK 	 72.80%
ALERT: the machine 10 stoped work - possible failure
FAIL 	 81.45%
ALERT: the machine 7 stoped work - possible failure
FAIL 	 86.94%
ALERT: the machine 3 stoped work - possible failure
FAIL 	 90.37%
OK 	 59.87%
OK 	 71.37%
ALERT: the machine 2 stoped work - possible failure
FAIL 	 87.13%
ALERT: the machine 3 stoped work - possible failure
FAIL 	 88.14%
OK 	 57.61%
OK 	 59.87%
OK 	 57.92%
OK 	 72.19%
OK 	 74.88%
OK 	 56.24%
FAIL 	 53.93%
OK 	 69.85%
OK 	 59.87%
OK 	 56.62%
OK 	 70.06%
OK 	 75.82%
ALERT: the machine 10 stoped work - possible failure
FAIL 	 86.05%
ALERT: the machine 6 stoped work - possible failure
FAIL 	 82.03%
WARNING: the machine 4 may fail, take the necessary care
FAIL 	 77.48%
OK 	 56.19%
OK 	 70.47%
ALERT: the machine 2 stoped work - possible failure
FAIL 	 81.39%
ALERT: the machine 2 stoped work - possible failure
FAIL 	 87.13%
ALERT: the machine 6 stoped work - possible failure
FAIL 	 81.64%

In [67]:
# data3.to_csv('../../ml_datasets/dataset_testing.csv', index=False)

In [68]:
new_df = pd.DataFrame(data=new_results, columns=new_results[0].keys())

In [69]:
data3 = pd.concat([new_df, data2], ignore_index=True)
# data3

In [70]:
# data = pd.read_csv('../../ml_datasets/dataset_edit.csv', index_col=None)
# data3=data
data3.to_csv('../../ml_datasets/dataset_testing.csv', index=False)

In [71]:
# # print(f'Status \t Result')
# for j in range(0,3):
#     new_results = []
#     for i in range(0,500):
#         new_data = generate_new_param()
#         response = requests.post(url+'/predict',data=json.dumps(new_data))
#         result = response.json()
#         predict = 'OK' if result['prediction'] == 0 else 'FAIL'
#         # print(f'{predict}')
#         print(f'{predict} \t {(result["score"]*100):.2f}%')
#         new_data['label'] = (result['prediction'])
#         # print(new_data)
#         new_results.append(new_data)
#         # data2.append(new_data, ignore_index=True)
#         # pd.concat(data2)
        
#     new_df = pd.DataFrame(data=new_results, columns=new_results[0].keys())

#     data3 = pd.concat([new_df, data], ignore_index=True)

#     data3.to_csv('../../ml_datasets/dataset_testing.csv', index=False)

#     print(f"New data interation {j}")
#     print("Update api")
#     time.sleep(120)
#     data2 = data3.sample(9000)